### PR TITLE
Write section on defining custom keyboard shortcuts

### PR DESCRIPTION
**Pull request by itsjeyd**
Hi Sacha,

I love what you are doing with the `emacs-notes` project. To (hopefully) help you out a little, I took the liberty to fork it and write a first draft of the "Set up your own keyboard shortcuts" section for the Emacs Lisp tutorial. Let me know what you think, I'd be happy to collaborate on this and add stuff you feel is missing.

### CODE REVIEW

**Comment by sachac** [comment]
You're awesome! =D

**Comment by sachac** [comment]
I'm thinking of doing some videos on borrowing interesting ideas from other people's config. =) Would you mind if I shared http://youtu.be/uP9qmhcI9IQ based on yours?

**Comment by itsjeyd** [comment]
Wow, this is really cool!! :blush: I wouldn't mind you sharing this video at all! And I'm glad you got a few ideas for your own config from it :)

**Comment by sachac** [comment]
Yay! =D

**Pull request merged**
